/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  DEFAULT_SETTINGS: () => DEFAULT_SETTINGS,
  GeminiAgentSettingTab: () => GeminiAgentSettingTab,
  MODEL_DISPLAY_NAMES: () => MODEL_DISPLAY_NAMES,
  VIEW_TYPE_GEMINI_CHAT: () => VIEW_TYPE_GEMINI_CHAT,
  default: () => GeminiAgentPlugin2
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// node_modules/.pnpm/@google+generative-ai@0.24.1/node_modules/@google/generative-ai/dist/index.mjs
var SchemaType;
(function(SchemaType2) {
  SchemaType2["STRING"] = "string";
  SchemaType2["NUMBER"] = "number";
  SchemaType2["INTEGER"] = "integer";
  SchemaType2["BOOLEAN"] = "boolean";
  SchemaType2["ARRAY"] = "array";
  SchemaType2["OBJECT"] = "object";
})(SchemaType || (SchemaType = {}));
var ExecutableCodeLanguage;
(function(ExecutableCodeLanguage2) {
  ExecutableCodeLanguage2["LANGUAGE_UNSPECIFIED"] = "language_unspecified";
  ExecutableCodeLanguage2["PYTHON"] = "python";
})(ExecutableCodeLanguage || (ExecutableCodeLanguage = {}));
var Outcome;
(function(Outcome2) {
  Outcome2["OUTCOME_UNSPECIFIED"] = "outcome_unspecified";
  Outcome2["OUTCOME_OK"] = "outcome_ok";
  Outcome2["OUTCOME_FAILED"] = "outcome_failed";
  Outcome2["OUTCOME_DEADLINE_EXCEEDED"] = "outcome_deadline_exceeded";
})(Outcome || (Outcome = {}));
var POSSIBLE_ROLES = ["user", "model", "function", "system"];
var HarmCategory;
(function(HarmCategory2) {
  HarmCategory2["HARM_CATEGORY_UNSPECIFIED"] = "HARM_CATEGORY_UNSPECIFIED";
  HarmCategory2["HARM_CATEGORY_HATE_SPEECH"] = "HARM_CATEGORY_HATE_SPEECH";
  HarmCategory2["HARM_CATEGORY_SEXUALLY_EXPLICIT"] = "HARM_CATEGORY_SEXUALLY_EXPLICIT";
  HarmCategory2["HARM_CATEGORY_HARASSMENT"] = "HARM_CATEGORY_HARASSMENT";
  HarmCategory2["HARM_CATEGORY_DANGEROUS_CONTENT"] = "HARM_CATEGORY_DANGEROUS_CONTENT";
  HarmCategory2["HARM_CATEGORY_CIVIC_INTEGRITY"] = "HARM_CATEGORY_CIVIC_INTEGRITY";
})(HarmCategory || (HarmCategory = {}));
var HarmBlockThreshold;
(function(HarmBlockThreshold2) {
  HarmBlockThreshold2["HARM_BLOCK_THRESHOLD_UNSPECIFIED"] = "HARM_BLOCK_THRESHOLD_UNSPECIFIED";
  HarmBlockThreshold2["BLOCK_LOW_AND_ABOVE"] = "BLOCK_LOW_AND_ABOVE";
  HarmBlockThreshold2["BLOCK_MEDIUM_AND_ABOVE"] = "BLOCK_MEDIUM_AND_ABOVE";
  HarmBlockThreshold2["BLOCK_ONLY_HIGH"] = "BLOCK_ONLY_HIGH";
  HarmBlockThreshold2["BLOCK_NONE"] = "BLOCK_NONE";
})(HarmBlockThreshold || (HarmBlockThreshold = {}));
var HarmProbability;
(function(HarmProbability2) {
  HarmProbability2["HARM_PROBABILITY_UNSPECIFIED"] = "HARM_PROBABILITY_UNSPECIFIED";
  HarmProbability2["NEGLIGIBLE"] = "NEGLIGIBLE";
  HarmProbability2["LOW"] = "LOW";
  HarmProbability2["MEDIUM"] = "MEDIUM";
  HarmProbability2["HIGH"] = "HIGH";
})(HarmProbability || (HarmProbability = {}));
var BlockReason;
(function(BlockReason2) {
  BlockReason2["BLOCKED_REASON_UNSPECIFIED"] = "BLOCKED_REASON_UNSPECIFIED";
  BlockReason2["SAFETY"] = "SAFETY";
  BlockReason2["OTHER"] = "OTHER";
})(BlockReason || (BlockReason = {}));
var FinishReason;
(function(FinishReason2) {
  FinishReason2["FINISH_REASON_UNSPECIFIED"] = "FINISH_REASON_UNSPECIFIED";
  FinishReason2["STOP"] = "STOP";
  FinishReason2["MAX_TOKENS"] = "MAX_TOKENS";
  FinishReason2["SAFETY"] = "SAFETY";
  FinishReason2["RECITATION"] = "RECITATION";
  FinishReason2["LANGUAGE"] = "LANGUAGE";
  FinishReason2["BLOCKLIST"] = "BLOCKLIST";
  FinishReason2["PROHIBITED_CONTENT"] = "PROHIBITED_CONTENT";
  FinishReason2["SPII"] = "SPII";
  FinishReason2["MALFORMED_FUNCTION_CALL"] = "MALFORMED_FUNCTION_CALL";
  FinishReason2["OTHER"] = "OTHER";
})(FinishReason || (FinishReason = {}));
var TaskType;
(function(TaskType2) {
  TaskType2["TASK_TYPE_UNSPECIFIED"] = "TASK_TYPE_UNSPECIFIED";
  TaskType2["RETRIEVAL_QUERY"] = "RETRIEVAL_QUERY";
  TaskType2["RETRIEVAL_DOCUMENT"] = "RETRIEVAL_DOCUMENT";
  TaskType2["SEMANTIC_SIMILARITY"] = "SEMANTIC_SIMILARITY";
  TaskType2["CLASSIFICATION"] = "CLASSIFICATION";
  TaskType2["CLUSTERING"] = "CLUSTERING";
})(TaskType || (TaskType = {}));
var FunctionCallingMode;
(function(FunctionCallingMode2) {
  FunctionCallingMode2["MODE_UNSPECIFIED"] = "MODE_UNSPECIFIED";
  FunctionCallingMode2["AUTO"] = "AUTO";
  FunctionCallingMode2["ANY"] = "ANY";
  FunctionCallingMode2["NONE"] = "NONE";
})(FunctionCallingMode || (FunctionCallingMode = {}));
var DynamicRetrievalMode;
(function(DynamicRetrievalMode2) {
  DynamicRetrievalMode2["MODE_UNSPECIFIED"] = "MODE_UNSPECIFIED";
  DynamicRetrievalMode2["MODE_DYNAMIC"] = "MODE_DYNAMIC";
})(DynamicRetrievalMode || (DynamicRetrievalMode = {}));
var GoogleGenerativeAIError = class extends Error {
  constructor(message) {
    super(`[GoogleGenerativeAI Error]: ${message}`);
  }
};
var GoogleGenerativeAIResponseError = class extends GoogleGenerativeAIError {
  constructor(message, response) {
    super(message);
    this.response = response;
  }
};
var GoogleGenerativeAIFetchError = class extends GoogleGenerativeAIError {
  constructor(message, status, statusText, errorDetails) {
    super(message);
    this.status = status;
    this.statusText = statusText;
    this.errorDetails = errorDetails;
  }
};
var GoogleGenerativeAIRequestInputError = class extends GoogleGenerativeAIError {
};
var GoogleGenerativeAIAbortError = class extends GoogleGenerativeAIError {
};
var DEFAULT_BASE_URL = "https://generativelanguage.googleapis.com";
var DEFAULT_API_VERSION = "v1beta";
var PACKAGE_VERSION = "0.24.1";
var PACKAGE_LOG_HEADER = "genai-js";
var Task;
(function(Task2) {
  Task2["GENERATE_CONTENT"] = "generateContent";
  Task2["STREAM_GENERATE_CONTENT"] = "streamGenerateContent";
  Task2["COUNT_TOKENS"] = "countTokens";
  Task2["EMBED_CONTENT"] = "embedContent";
  Task2["BATCH_EMBED_CONTENTS"] = "batchEmbedContents";
})(Task || (Task = {}));
var RequestUrl = class {
  constructor(model, task, apiKey, stream, requestOptions) {
    this.model = model;
    this.task = task;
    this.apiKey = apiKey;
    this.stream = stream;
    this.requestOptions = requestOptions;
  }
  toString() {
    var _a, _b;
    const apiVersion = ((_a = this.requestOptions) === null || _a === void 0 ? void 0 : _a.apiVersion) || DEFAULT_API_VERSION;
    const baseUrl = ((_b = this.requestOptions) === null || _b === void 0 ? void 0 : _b.baseUrl) || DEFAULT_BASE_URL;
    let url = `${baseUrl}/${apiVersion}/${this.model}:${this.task}`;
    if (this.stream) {
      url += "?alt=sse";
    }
    return url;
  }
};
function getClientHeaders(requestOptions) {
  const clientHeaders = [];
  if (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.apiClient) {
    clientHeaders.push(requestOptions.apiClient);
  }
  clientHeaders.push(`${PACKAGE_LOG_HEADER}/${PACKAGE_VERSION}`);
  return clientHeaders.join(" ");
}
async function getHeaders(url) {
  var _a;
  const headers = new Headers();
  headers.append("Content-Type", "application/json");
  headers.append("x-goog-api-client", getClientHeaders(url.requestOptions));
  headers.append("x-goog-api-key", url.apiKey);
  let customHeaders = (_a = url.requestOptions) === null || _a === void 0 ? void 0 : _a.customHeaders;
  if (customHeaders) {
    if (!(customHeaders instanceof Headers)) {
      try {
        customHeaders = new Headers(customHeaders);
      } catch (e) {
        throw new GoogleGenerativeAIRequestInputError(`unable to convert customHeaders value ${JSON.stringify(customHeaders)} to Headers: ${e.message}`);
      }
    }
    for (const [headerName, headerValue] of customHeaders.entries()) {
      if (headerName === "x-goog-api-key") {
        throw new GoogleGenerativeAIRequestInputError(`Cannot set reserved header name ${headerName}`);
      } else if (headerName === "x-goog-api-client") {
        throw new GoogleGenerativeAIRequestInputError(`Header name ${headerName} can only be set using the apiClient field`);
      }
      headers.append(headerName, headerValue);
    }
  }
  return headers;
}
async function constructModelRequest(model, task, apiKey, stream, body, requestOptions) {
  const url = new RequestUrl(model, task, apiKey, stream, requestOptions);
  return {
    url: url.toString(),
    fetchOptions: Object.assign(Object.assign({}, buildFetchOptions(requestOptions)), { method: "POST", headers: await getHeaders(url), body })
  };
}
async function makeModelRequest(model, task, apiKey, stream, body, requestOptions = {}, fetchFn = fetch) {
  const { url, fetchOptions } = await constructModelRequest(model, task, apiKey, stream, body, requestOptions);
  return makeRequest(url, fetchOptions, fetchFn);
}
async function makeRequest(url, fetchOptions, fetchFn = fetch) {
  let response;
  try {
    response = await fetchFn(url, fetchOptions);
  } catch (e) {
    handleResponseError(e, url);
  }
  if (!response.ok) {
    await handleResponseNotOk(response, url);
  }
  return response;
}
function handleResponseError(e, url) {
  let err = e;
  if (err.name === "AbortError") {
    err = new GoogleGenerativeAIAbortError(`Request aborted when fetching ${url.toString()}: ${e.message}`);
    err.stack = e.stack;
  } else if (!(e instanceof GoogleGenerativeAIFetchError || e instanceof GoogleGenerativeAIRequestInputError)) {
    err = new GoogleGenerativeAIError(`Error fetching from ${url.toString()}: ${e.message}`);
    err.stack = e.stack;
  }
  throw err;
}
async function handleResponseNotOk(response, url) {
  let message = "";
  let errorDetails;
  try {
    const json = await response.json();
    message = json.error.message;
    if (json.error.details) {
      message += ` ${JSON.stringify(json.error.details)}`;
      errorDetails = json.error.details;
    }
  } catch (e) {
  }
  throw new GoogleGenerativeAIFetchError(`Error fetching from ${url.toString()}: [${response.status} ${response.statusText}] ${message}`, response.status, response.statusText, errorDetails);
}
function buildFetchOptions(requestOptions) {
  const fetchOptions = {};
  if ((requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.signal) !== void 0 || (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeout) >= 0) {
    const controller = new AbortController();
    if ((requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeout) >= 0) {
      setTimeout(() => controller.abort(), requestOptions.timeout);
    }
    if (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.signal) {
      requestOptions.signal.addEventListener("abort", () => {
        controller.abort();
      });
    }
    fetchOptions.signal = controller.signal;
  }
  return fetchOptions;
}
function addHelpers(response) {
  response.text = () => {
    if (response.candidates && response.candidates.length > 0) {
      if (response.candidates.length > 1) {
        console.warn(`This response had ${response.candidates.length} candidates. Returning text from the first candidate only. Access response.candidates directly to use the other candidates.`);
      }
      if (hadBadFinishReason(response.candidates[0])) {
        throw new GoogleGenerativeAIResponseError(`${formatBlockErrorMessage(response)}`, response);
      }
      return getText(response);
    } else if (response.promptFeedback) {
      throw new GoogleGenerativeAIResponseError(`Text not available. ${formatBlockErrorMessage(response)}`, response);
    }
    return "";
  };
  response.functionCall = () => {
    if (response.candidates && response.candidates.length > 0) {
      if (response.candidates.length > 1) {
        console.warn(`This response had ${response.candidates.length} candidates. Returning function calls from the first candidate only. Access response.candidates directly to use the other candidates.`);
      }
      if (hadBadFinishReason(response.candidates[0])) {
        throw new GoogleGenerativeAIResponseError(`${formatBlockErrorMessage(response)}`, response);
      }
      console.warn(`response.functionCall() is deprecated. Use response.functionCalls() instead.`);
      return getFunctionCalls(response)[0];
    } else if (response.promptFeedback) {
      throw new GoogleGenerativeAIResponseError(`Function call not available. ${formatBlockErrorMessage(response)}`, response);
    }
    return void 0;
  };
  response.functionCalls = () => {
    if (response.candidates && response.candidates.length > 0) {
      if (response.candidates.length > 1) {
        console.warn(`This response had ${response.candidates.length} candidates. Returning function calls from the first candidate only. Access response.candidates directly to use the other candidates.`);
      }
      if (hadBadFinishReason(response.candidates[0])) {
        throw new GoogleGenerativeAIResponseError(`${formatBlockErrorMessage(response)}`, response);
      }
      return getFunctionCalls(response);
    } else if (response.promptFeedback) {
      throw new GoogleGenerativeAIResponseError(`Function call not available. ${formatBlockErrorMessage(response)}`, response);
    }
    return void 0;
  };
  return response;
}
function getText(response) {
  var _a, _b, _c, _d;
  const textStrings = [];
  if ((_b = (_a = response.candidates) === null || _a === void 0 ? void 0 : _a[0].content) === null || _b === void 0 ? void 0 : _b.parts) {
    for (const part of (_d = (_c = response.candidates) === null || _c === void 0 ? void 0 : _c[0].content) === null || _d === void 0 ? void 0 : _d.parts) {
      if (part.text) {
        textStrings.push(part.text);
      }
      if (part.executableCode) {
        textStrings.push("\n```" + part.executableCode.language + "\n" + part.executableCode.code + "\n```\n");
      }
      if (part.codeExecutionResult) {
        textStrings.push("\n```\n" + part.codeExecutionResult.output + "\n```\n");
      }
    }
  }
  if (textStrings.length > 0) {
    return textStrings.join("");
  } else {
    return "";
  }
}
function getFunctionCalls(response) {
  var _a, _b, _c, _d;
  const functionCalls = [];
  if ((_b = (_a = response.candidates) === null || _a === void 0 ? void 0 : _a[0].content) === null || _b === void 0 ? void 0 : _b.parts) {
    for (const part of (_d = (_c = response.candidates) === null || _c === void 0 ? void 0 : _c[0].content) === null || _d === void 0 ? void 0 : _d.parts) {
      if (part.functionCall) {
        functionCalls.push(part.functionCall);
      }
    }
  }
  if (functionCalls.length > 0) {
    return functionCalls;
  } else {
    return void 0;
  }
}
var badFinishReasons = [
  FinishReason.RECITATION,
  FinishReason.SAFETY,
  FinishReason.LANGUAGE
];
function hadBadFinishReason(candidate) {
  return !!candidate.finishReason && badFinishReasons.includes(candidate.finishReason);
}
function formatBlockErrorMessage(response) {
  var _a, _b, _c;
  let message = "";
  if ((!response.candidates || response.candidates.length === 0) && response.promptFeedback) {
    message += "Response was blocked";
    if ((_a = response.promptFeedback) === null || _a === void 0 ? void 0 : _a.blockReason) {
      message += ` due to ${response.promptFeedback.blockReason}`;
    }
    if ((_b = response.promptFeedback) === null || _b === void 0 ? void 0 : _b.blockReasonMessage) {
      message += `: ${response.promptFeedback.blockReasonMessage}`;
    }
  } else if ((_c = response.candidates) === null || _c === void 0 ? void 0 : _c[0]) {
    const firstCandidate = response.candidates[0];
    if (hadBadFinishReason(firstCandidate)) {
      message += `Candidate was blocked due to ${firstCandidate.finishReason}`;
      if (firstCandidate.finishMessage) {
        message += `: ${firstCandidate.finishMessage}`;
      }
    }
  }
  return message;
}
function __await(v) {
  return this instanceof __await ? (this.v = v, this) : new __await(v);
}
function __asyncGenerator(thisArg, _arguments, generator) {
  if (!Symbol.asyncIterator) throw new TypeError("Symbol.asyncIterator is not defined.");
  var g = generator.apply(thisArg, _arguments || []), i, q = [];
  return i = {}, verb("next"), verb("throw"), verb("return"), i[Symbol.asyncIterator] = function() {
    return this;
  }, i;
  function verb(n) {
    if (g[n]) i[n] = function(v) {
      return new Promise(function(a, b) {
        q.push([n, v, a, b]) > 1 || resume(n, v);
      });
    };
  }
  function resume(n, v) {
    try {
      step(g[n](v));
    } catch (e) {
      settle(q[0][3], e);
    }
  }
  function step(r) {
    r.value instanceof __await ? Promise.resolve(r.value.v).then(fulfill, reject) : settle(q[0][2], r);
  }
  function fulfill(value) {
    resume("next", value);
  }
  function reject(value) {
    resume("throw", value);
  }
  function settle(f, v) {
    if (f(v), q.shift(), q.length) resume(q[0][0], q[0][1]);
  }
}
var responseLineRE = /^data\: (.*)(?:\n\n|\r\r|\r\n\r\n)/;
function processStream(response) {
  const inputStream = response.body.pipeThrough(new TextDecoderStream("utf8", { fatal: true }));
  const responseStream = getResponseStream(inputStream);
  const [stream1, stream2] = responseStream.tee();
  return {
    stream: generateResponseSequence(stream1),
    response: getResponsePromise(stream2)
  };
}
async function getResponsePromise(stream) {
  const allResponses = [];
  const reader = stream.getReader();
  while (true) {
    const { done, value } = await reader.read();
    if (done) {
      return addHelpers(aggregateResponses(allResponses));
    }
    allResponses.push(value);
  }
}
function generateResponseSequence(stream) {
  return __asyncGenerator(this, arguments, function* generateResponseSequence_1() {
    const reader = stream.getReader();
    while (true) {
      const { value, done } = yield __await(reader.read());
      if (done) {
        break;
      }
      yield yield __await(addHelpers(value));
    }
  });
}
function getResponseStream(inputStream) {
  const reader = inputStream.getReader();
  const stream = new ReadableStream({
    start(controller) {
      let currentText = "";
      return pump();
      function pump() {
        return reader.read().then(({ value, done }) => {
          if (done) {
            if (currentText.trim()) {
              controller.error(new GoogleGenerativeAIError("Failed to parse stream"));
              return;
            }
            controller.close();
            return;
          }
          currentText += value;
          let match = currentText.match(responseLineRE);
          let parsedResponse;
          while (match) {
            try {
              parsedResponse = JSON.parse(match[1]);
            } catch (e) {
              controller.error(new GoogleGenerativeAIError(`Error parsing JSON response: "${match[1]}"`));
              return;
            }
            controller.enqueue(parsedResponse);
            currentText = currentText.substring(match[0].length);
            match = currentText.match(responseLineRE);
          }
          return pump();
        }).catch((e) => {
          let err = e;
          err.stack = e.stack;
          if (err.name === "AbortError") {
            err = new GoogleGenerativeAIAbortError("Request aborted when reading from the stream");
          } else {
            err = new GoogleGenerativeAIError("Error reading from the stream");
          }
          throw err;
        });
      }
    }
  });
  return stream;
}
function aggregateResponses(responses) {
  const lastResponse = responses[responses.length - 1];
  const aggregatedResponse = {
    promptFeedback: lastResponse === null || lastResponse === void 0 ? void 0 : lastResponse.promptFeedback
  };
  for (const response of responses) {
    if (response.candidates) {
      let candidateIndex = 0;
      for (const candidate of response.candidates) {
        if (!aggregatedResponse.candidates) {
          aggregatedResponse.candidates = [];
        }
        if (!aggregatedResponse.candidates[candidateIndex]) {
          aggregatedResponse.candidates[candidateIndex] = {
            index: candidateIndex
          };
        }
        aggregatedResponse.candidates[candidateIndex].citationMetadata = candidate.citationMetadata;
        aggregatedResponse.candidates[candidateIndex].groundingMetadata = candidate.groundingMetadata;
        aggregatedResponse.candidates[candidateIndex].finishReason = candidate.finishReason;
        aggregatedResponse.candidates[candidateIndex].finishMessage = candidate.finishMessage;
        aggregatedResponse.candidates[candidateIndex].safetyRatings = candidate.safetyRatings;
        if (candidate.content && candidate.content.parts) {
          if (!aggregatedResponse.candidates[candidateIndex].content) {
            aggregatedResponse.candidates[candidateIndex].content = {
              role: candidate.content.role || "user",
              parts: []
            };
          }
          const newPart = {};
          for (const part of candidate.content.parts) {
            if (part.text) {
              newPart.text = part.text;
            }
            if (part.functionCall) {
              newPart.functionCall = part.functionCall;
            }
            if (part.executableCode) {
              newPart.executableCode = part.executableCode;
            }
            if (part.codeExecutionResult) {
              newPart.codeExecutionResult = part.codeExecutionResult;
            }
            if (Object.keys(newPart).length === 0) {
              newPart.text = "";
            }
            aggregatedResponse.candidates[candidateIndex].content.parts.push(newPart);
          }
        }
      }
      candidateIndex++;
    }
    if (response.usageMetadata) {
      aggregatedResponse.usageMetadata = response.usageMetadata;
    }
  }
  return aggregatedResponse;
}
async function generateContentStream(apiKey, model, params, requestOptions) {
  const response = await makeModelRequest(
    model,
    Task.STREAM_GENERATE_CONTENT,
    apiKey,
    /* stream */
    true,
    JSON.stringify(params),
    requestOptions
  );
  return processStream(response);
}
async function generateContent(apiKey, model, params, requestOptions) {
  const response = await makeModelRequest(
    model,
    Task.GENERATE_CONTENT,
    apiKey,
    /* stream */
    false,
    JSON.stringify(params),
    requestOptions
  );
  const responseJson = await response.json();
  const enhancedResponse = addHelpers(responseJson);
  return {
    response: enhancedResponse
  };
}
function formatSystemInstruction(input) {
  if (input == null) {
    return void 0;
  } else if (typeof input === "string") {
    return { role: "system", parts: [{ text: input }] };
  } else if (input.text) {
    return { role: "system", parts: [input] };
  } else if (input.parts) {
    if (!input.role) {
      return { role: "system", parts: input.parts };
    } else {
      return input;
    }
  }
}
function formatNewContent(request) {
  let newParts = [];
  if (typeof request === "string") {
    newParts = [{ text: request }];
  } else {
    for (const partOrString of request) {
      if (typeof partOrString === "string") {
        newParts.push({ text: partOrString });
      } else {
        newParts.push(partOrString);
      }
    }
  }
  return assignRoleToPartsAndValidateSendMessageRequest(newParts);
}
function assignRoleToPartsAndValidateSendMessageRequest(parts) {
  const userContent = { role: "user", parts: [] };
  const functionContent = { role: "function", parts: [] };
  let hasUserContent = false;
  let hasFunctionContent = false;
  for (const part of parts) {
    if ("functionResponse" in part) {
      functionContent.parts.push(part);
      hasFunctionContent = true;
    } else {
      userContent.parts.push(part);
      hasUserContent = true;
    }
  }
  if (hasUserContent && hasFunctionContent) {
    throw new GoogleGenerativeAIError("Within a single message, FunctionResponse cannot be mixed with other type of part in the request for sending chat message.");
  }
  if (!hasUserContent && !hasFunctionContent) {
    throw new GoogleGenerativeAIError("No content is provided for sending chat message.");
  }
  if (hasUserContent) {
    return userContent;
  }
  return functionContent;
}
function formatCountTokensInput(params, modelParams) {
  var _a;
  let formattedGenerateContentRequest = {
    model: modelParams === null || modelParams === void 0 ? void 0 : modelParams.model,
    generationConfig: modelParams === null || modelParams === void 0 ? void 0 : modelParams.generationConfig,
    safetySettings: modelParams === null || modelParams === void 0 ? void 0 : modelParams.safetySettings,
    tools: modelParams === null || modelParams === void 0 ? void 0 : modelParams.tools,
    toolConfig: modelParams === null || modelParams === void 0 ? void 0 : modelParams.toolConfig,
    systemInstruction: modelParams === null || modelParams === void 0 ? void 0 : modelParams.systemInstruction,
    cachedContent: (_a = modelParams === null || modelParams === void 0 ? void 0 : modelParams.cachedContent) === null || _a === void 0 ? void 0 : _a.name,
    contents: []
  };
  const containsGenerateContentRequest = params.generateContentRequest != null;
  if (params.contents) {
    if (containsGenerateContentRequest) {
      throw new GoogleGenerativeAIRequestInputError("CountTokensRequest must have one of contents or generateContentRequest, not both.");
    }
    formattedGenerateContentRequest.contents = params.contents;
  } else if (containsGenerateContentRequest) {
    formattedGenerateContentRequest = Object.assign(Object.assign({}, formattedGenerateContentRequest), params.generateContentRequest);
  } else {
    const content = formatNewContent(params);
    formattedGenerateContentRequest.contents = [content];
  }
  return { generateContentRequest: formattedGenerateContentRequest };
}
function formatGenerateContentInput(params) {
  let formattedRequest;
  if (params.contents) {
    formattedRequest = params;
  } else {
    const content = formatNewContent(params);
    formattedRequest = { contents: [content] };
  }
  if (params.systemInstruction) {
    formattedRequest.systemInstruction = formatSystemInstruction(params.systemInstruction);
  }
  return formattedRequest;
}
function formatEmbedContentInput(params) {
  if (typeof params === "string" || Array.isArray(params)) {
    const content = formatNewContent(params);
    return { content };
  }
  return params;
}
var VALID_PART_FIELDS = [
  "text",
  "inlineData",
  "functionCall",
  "functionResponse",
  "executableCode",
  "codeExecutionResult"
];
var VALID_PARTS_PER_ROLE = {
  user: ["text", "inlineData"],
  function: ["functionResponse"],
  model: ["text", "functionCall", "executableCode", "codeExecutionResult"],
  // System instructions shouldn't be in history anyway.
  system: ["text"]
};
function validateChatHistory(history) {
  let prevContent = false;
  for (const currContent of history) {
    const { role, parts } = currContent;
    if (!prevContent && role !== "user") {
      throw new GoogleGenerativeAIError(`First content should be with role 'user', got ${role}`);
    }
    if (!POSSIBLE_ROLES.includes(role)) {
      throw new GoogleGenerativeAIError(`Each item should include role field. Got ${role} but valid roles are: ${JSON.stringify(POSSIBLE_ROLES)}`);
    }
    if (!Array.isArray(parts)) {
      throw new GoogleGenerativeAIError("Content should have 'parts' property with an array of Parts");
    }
    if (parts.length === 0) {
      throw new GoogleGenerativeAIError("Each Content should have at least one part");
    }
    const countFields = {
      text: 0,
      inlineData: 0,
      functionCall: 0,
      functionResponse: 0,
      fileData: 0,
      executableCode: 0,
      codeExecutionResult: 0
    };
    for (const part of parts) {
      for (const key of VALID_PART_FIELDS) {
        if (key in part) {
          countFields[key] += 1;
        }
      }
    }
    const validParts = VALID_PARTS_PER_ROLE[role];
    for (const key of VALID_PART_FIELDS) {
      if (!validParts.includes(key) && countFields[key] > 0) {
        throw new GoogleGenerativeAIError(`Content with role '${role}' can't contain '${key}' part`);
      }
    }
    prevContent = true;
  }
}
function isValidResponse(response) {
  var _a;
  if (response.candidates === void 0 || response.candidates.length === 0) {
    return false;
  }
  const content = (_a = response.candidates[0]) === null || _a === void 0 ? void 0 : _a.content;
  if (content === void 0) {
    return false;
  }
  if (content.parts === void 0 || content.parts.length === 0) {
    return false;
  }
  for (const part of content.parts) {
    if (part === void 0 || Object.keys(part).length === 0) {
      return false;
    }
    if (part.text !== void 0 && part.text === "") {
      return false;
    }
  }
  return true;
}
var SILENT_ERROR = "SILENT_ERROR";
var ChatSession = class {
  constructor(apiKey, model, params, _requestOptions = {}) {
    this.model = model;
    this.params = params;
    this._requestOptions = _requestOptions;
    this._history = [];
    this._sendPromise = Promise.resolve();
    this._apiKey = apiKey;
    if (params === null || params === void 0 ? void 0 : params.history) {
      validateChatHistory(params.history);
      this._history = params.history;
    }
  }
  /**
   * Gets the chat history so far. Blocked prompts are not added to history.
   * Blocked candidates are not added to history, nor are the prompts that
   * generated them.
   */
  async getHistory() {
    await this._sendPromise;
    return this._history;
  }
  /**
   * Sends a chat message and receives a non-streaming
   * {@link GenerateContentResult}.
   *
   * Fields set in the optional {@link SingleRequestOptions} parameter will
   * take precedence over the {@link RequestOptions} values provided to
   * {@link GoogleGenerativeAI.getGenerativeModel }.
   */
  async sendMessage(request, requestOptions = {}) {
    var _a, _b, _c, _d, _e, _f;
    await this._sendPromise;
    const newContent = formatNewContent(request);
    const generateContentRequest = {
      safetySettings: (_a = this.params) === null || _a === void 0 ? void 0 : _a.safetySettings,
      generationConfig: (_b = this.params) === null || _b === void 0 ? void 0 : _b.generationConfig,
      tools: (_c = this.params) === null || _c === void 0 ? void 0 : _c.tools,
      toolConfig: (_d = this.params) === null || _d === void 0 ? void 0 : _d.toolConfig,
      systemInstruction: (_e = this.params) === null || _e === void 0 ? void 0 : _e.systemInstruction,
      cachedContent: (_f = this.params) === null || _f === void 0 ? void 0 : _f.cachedContent,
      contents: [...this._history, newContent]
    };
    const chatSessionRequestOptions = Object.assign(Object.assign({}, this._requestOptions), requestOptions);
    let finalResult;
    this._sendPromise = this._sendPromise.then(() => generateContent(this._apiKey, this.model, generateContentRequest, chatSessionRequestOptions)).then((result) => {
      var _a2;
      if (isValidResponse(result.response)) {
        this._history.push(newContent);
        const responseContent = Object.assign({
          parts: [],
          // Response seems to come back without a role set.
          role: "model"
        }, (_a2 = result.response.candidates) === null || _a2 === void 0 ? void 0 : _a2[0].content);
        this._history.push(responseContent);
      } else {
        const blockErrorMessage = formatBlockErrorMessage(result.response);
        if (blockErrorMessage) {
          console.warn(`sendMessage() was unsuccessful. ${blockErrorMessage}. Inspect response object for details.`);
        }
      }
      finalResult = result;
    }).catch((e) => {
      this._sendPromise = Promise.resolve();
      throw e;
    });
    await this._sendPromise;
    return finalResult;
  }
  /**
   * Sends a chat message and receives the response as a
   * {@link GenerateContentStreamResult} containing an iterable stream
   * and a response promise.
   *
   * Fields set in the optional {@link SingleRequestOptions} parameter will
   * take precedence over the {@link RequestOptions} values provided to
   * {@link GoogleGenerativeAI.getGenerativeModel }.
   */
  async sendMessageStream(request, requestOptions = {}) {
    var _a, _b, _c, _d, _e, _f;
    await this._sendPromise;
    const newContent = formatNewContent(request);
    const generateContentRequest = {
      safetySettings: (_a = this.params) === null || _a === void 0 ? void 0 : _a.safetySettings,
      generationConfig: (_b = this.params) === null || _b === void 0 ? void 0 : _b.generationConfig,
      tools: (_c = this.params) === null || _c === void 0 ? void 0 : _c.tools,
      toolConfig: (_d = this.params) === null || _d === void 0 ? void 0 : _d.toolConfig,
      systemInstruction: (_e = this.params) === null || _e === void 0 ? void 0 : _e.systemInstruction,
      cachedContent: (_f = this.params) === null || _f === void 0 ? void 0 : _f.cachedContent,
      contents: [...this._history, newContent]
    };
    const chatSessionRequestOptions = Object.assign(Object.assign({}, this._requestOptions), requestOptions);
    const streamPromise = generateContentStream(this._apiKey, this.model, generateContentRequest, chatSessionRequestOptions);
    this._sendPromise = this._sendPromise.then(() => streamPromise).catch((_ignored) => {
      throw new Error(SILENT_ERROR);
    }).then((streamResult) => streamResult.response).then((response) => {
      if (isValidResponse(response)) {
        this._history.push(newContent);
        const responseContent = Object.assign({}, response.candidates[0].content);
        if (!responseContent.role) {
          responseContent.role = "model";
        }
        this._history.push(responseContent);
      } else {
        const blockErrorMessage = formatBlockErrorMessage(response);
        if (blockErrorMessage) {
          console.warn(`sendMessageStream() was unsuccessful. ${blockErrorMessage}. Inspect response object for details.`);
        }
      }
    }).catch((e) => {
      if (e.message !== SILENT_ERROR) {
        console.error(e);
      }
    });
    return streamPromise;
  }
};
async function countTokens(apiKey, model, params, singleRequestOptions) {
  const response = await makeModelRequest(model, Task.COUNT_TOKENS, apiKey, false, JSON.stringify(params), singleRequestOptions);
  return response.json();
}
async function embedContent(apiKey, model, params, requestOptions) {
  const response = await makeModelRequest(model, Task.EMBED_CONTENT, apiKey, false, JSON.stringify(params), requestOptions);
  return response.json();
}
async function batchEmbedContents(apiKey, model, params, requestOptions) {
  const requestsWithModel = params.requests.map((request) => {
    return Object.assign(Object.assign({}, request), { model });
  });
  const response = await makeModelRequest(model, Task.BATCH_EMBED_CONTENTS, apiKey, false, JSON.stringify({ requests: requestsWithModel }), requestOptions);
  return response.json();
}
var GenerativeModel = class {
  constructor(apiKey, modelParams, _requestOptions = {}) {
    this.apiKey = apiKey;
    this._requestOptions = _requestOptions;
    if (modelParams.model.includes("/")) {
      this.model = modelParams.model;
    } else {
      this.model = `models/${modelParams.model}`;
    }
    this.generationConfig = modelParams.generationConfig || {};
    this.safetySettings = modelParams.safetySettings || [];
    this.tools = modelParams.tools;
    this.toolConfig = modelParams.toolConfig;
    this.systemInstruction = formatSystemInstruction(modelParams.systemInstruction);
    this.cachedContent = modelParams.cachedContent;
  }
  /**
   * Makes a single non-streaming call to the model
   * and returns an object containing a single {@link GenerateContentResponse}.
   *
   * Fields set in the optional {@link SingleRequestOptions} parameter will
   * take precedence over the {@link RequestOptions} values provided to
   * {@link GoogleGenerativeAI.getGenerativeModel }.
   */
  async generateContent(request, requestOptions = {}) {
    var _a;
    const formattedParams = formatGenerateContentInput(request);
    const generativeModelRequestOptions = Object.assign(Object.assign({}, this._requestOptions), requestOptions);
    return generateContent(this.apiKey, this.model, Object.assign({ generationConfig: this.generationConfig, safetySettings: this.safetySettings, tools: this.tools, toolConfig: this.toolConfig, systemInstruction: this.systemInstruction, cachedContent: (_a = this.cachedContent) === null || _a === void 0 ? void 0 : _a.name }, formattedParams), generativeModelRequestOptions);
  }
  /**
   * Makes a single streaming call to the model and returns an object
   * containing an iterable stream that iterates over all chunks in the
   * streaming response as well as a promise that returns the final
   * aggregated response.
   *
   * Fields set in the optional {@link SingleRequestOptions} parameter will
   * take precedence over the {@link RequestOptions} values provided to
   * {@link GoogleGenerativeAI.getGenerativeModel }.
   */
  async generateContentStream(request, requestOptions = {}) {
    var _a;
    const formattedParams = formatGenerateContentInput(request);
    const generativeModelRequestOptions = Object.assign(Object.assign({}, this._requestOptions), requestOptions);
    return generateContentStream(this.apiKey, this.model, Object.assign({ generationConfig: this.generationConfig, safetySettings: this.safetySettings, tools: this.tools, toolConfig: this.toolConfig, systemInstruction: this.systemInstruction, cachedContent: (_a = this.cachedContent) === null || _a === void 0 ? void 0 : _a.name }, formattedParams), generativeModelRequestOptions);
  }
  /**
   * Gets a new {@link ChatSession} instance which can be used for
   * multi-turn chats.
   */
  startChat(startChatParams) {
    var _a;
    return new ChatSession(this.apiKey, this.model, Object.assign({ generationConfig: this.generationConfig, safetySettings: this.safetySettings, tools: this.tools, toolConfig: this.toolConfig, systemInstruction: this.systemInstruction, cachedContent: (_a = this.cachedContent) === null || _a === void 0 ? void 0 : _a.name }, startChatParams), this._requestOptions);
  }
  /**
   * Counts the tokens in the provided request.
   *
   * Fields set in the optional {@link SingleRequestOptions} parameter will
   * take precedence over the {@link RequestOptions} values provided to
   * {@link GoogleGenerativeAI.getGenerativeModel }.
   */
  async countTokens(request, requestOptions = {}) {
    const formattedParams = formatCountTokensInput(request, {
      model: this.model,
      generationConfig: this.generationConfig,
      safetySettings: this.safetySettings,
      tools: this.tools,
      toolConfig: this.toolConfig,
      systemInstruction: this.systemInstruction,
      cachedContent: this.cachedContent
    });
    const generativeModelRequestOptions = Object.assign(Object.assign({}, this._requestOptions), requestOptions);
    return countTokens(this.apiKey, this.model, formattedParams, generativeModelRequestOptions);
  }
  /**
   * Embeds the provided content.
   *
   * Fields set in the optional {@link SingleRequestOptions} parameter will
   * take precedence over the {@link RequestOptions} values provided to
   * {@link GoogleGenerativeAI.getGenerativeModel }.
   */
  async embedContent(request, requestOptions = {}) {
    const formattedParams = formatEmbedContentInput(request);
    const generativeModelRequestOptions = Object.assign(Object.assign({}, this._requestOptions), requestOptions);
    return embedContent(this.apiKey, this.model, formattedParams, generativeModelRequestOptions);
  }
  /**
   * Embeds an array of {@link EmbedContentRequest}s.
   *
   * Fields set in the optional {@link SingleRequestOptions} parameter will
   * take precedence over the {@link RequestOptions} values provided to
   * {@link GoogleGenerativeAI.getGenerativeModel }.
   */
  async batchEmbedContents(batchEmbedContentRequest, requestOptions = {}) {
    const generativeModelRequestOptions = Object.assign(Object.assign({}, this._requestOptions), requestOptions);
    return batchEmbedContents(this.apiKey, this.model, batchEmbedContentRequest, generativeModelRequestOptions);
  }
};
var GoogleGenerativeAI = class {
  constructor(apiKey) {
    this.apiKey = apiKey;
  }
  /**
   * Gets a {@link GenerativeModel} instance for the provided model name.
   */
  getGenerativeModel(modelParams, requestOptions) {
    if (!modelParams.model) {
      throw new GoogleGenerativeAIError(`Must provide a model name. Example: genai.getGenerativeModel({ model: 'my-model-name' })`);
    }
    return new GenerativeModel(this.apiKey, modelParams, requestOptions);
  }
  /**
   * Creates a {@link GenerativeModel} instance from provided content cache.
   */
  getGenerativeModelFromCachedContent(cachedContent, modelParams, requestOptions) {
    if (!cachedContent.name) {
      throw new GoogleGenerativeAIRequestInputError("Cached content must contain a `name` field.");
    }
    if (!cachedContent.model) {
      throw new GoogleGenerativeAIRequestInputError("Cached content must contain a `model` field.");
    }
    const disallowedDuplicates = ["model", "systemInstruction"];
    for (const key of disallowedDuplicates) {
      if ((modelParams === null || modelParams === void 0 ? void 0 : modelParams[key]) && cachedContent[key] && (modelParams === null || modelParams === void 0 ? void 0 : modelParams[key]) !== cachedContent[key]) {
        if (key === "model") {
          const modelParamsComp = modelParams.model.startsWith("models/") ? modelParams.model.replace("models/", "") : modelParams.model;
          const cachedContentComp = cachedContent.model.startsWith("models/") ? cachedContent.model.replace("models/", "") : cachedContent.model;
          if (modelParamsComp === cachedContentComp) {
            continue;
          }
        }
        throw new GoogleGenerativeAIRequestInputError(`Different value for "${key}" specified in modelParams (${modelParams[key]}) and cachedContent (${cachedContent[key]})`);
      }
    }
    const modelParamsFromCache = Object.assign(Object.assign({}, modelParams), { model: cachedContent.model, tools: cachedContent.tools, toolConfig: cachedContent.toolConfig, systemInstruction: cachedContent.systemInstruction, cachedContent });
    return new GenerativeModel(this.apiKey, modelParamsFromCache, requestOptions);
  }
};

// src/view.ts
var import_obsidian2 = require("obsidian");

// src/tools.ts
var getObsidianTools = (app, excludedPaths = []) => {
  const isExcluded = (path) => {
    return excludedPaths.some((excluded) => path.startsWith(excluded.trim()));
  };
  const isFile = (file) => {
    return "extension" in file;
  };
  const isFolder = (file) => {
    return "children" in file;
  };
  return {
    create_note: async ({ path, content, tags }) => {
      if (isExcluded(path)) return `Error: Access to ${path} is excluded in settings.`;
      try {
        const fullContent = tags && tags.length > 0 ? `---
tags: [${tags.join(", ")}]
---
${content}` : content;
        const file = await app.vault.create(path, fullContent);
        return `Successfully created note at ${file.path}`;
      } catch (error) {
        return `Error creating note: ${error instanceof Error ? error.message : String(error)}`;
      }
    },
    update_note: async ({ path, new_content }) => {
      if (isExcluded(path)) return `Error: Access to ${path} is excluded in settings.`;
      try {
        const file = app.vault.getAbstractFileByPath(path);
        if (file && isFile(file)) {
          await app.vault.modify(file, new_content);
          return `Successfully updated note at ${path}`;
        }
        return `Error: File not found at ${path}`;
      } catch (error) {
        return `Error updating note: ${error instanceof Error ? error.message : String(error)}`;
      }
    },
    read_note: async ({ path }) => {
      if (isExcluded(path)) return `Error: Access to ${path} is excluded in settings.`;
      try {
        const file = app.vault.getAbstractFileByPath(path);
        if (file && isFile(file)) {
          return await app.vault.cachedRead(file);
        }
        return `Error: File not found at ${path}`;
      } catch (error) {
        return `Error reading note: ${error instanceof Error ? error.message : String(error)}`;
      }
    },
    get_metadata: ({ path }) => {
      if (isExcluded(path)) return Promise.resolve(`Error: Access to ${path} is excluded in settings.`);
      try {
        const file = app.vault.getAbstractFileByPath(path);
        if (file && isFile(file)) {
          const cache = app.metadataCache.getFileCache(file);
          return Promise.resolve(JSON.stringify(cache, null, 2));
        }
        return Promise.resolve(`Error: File not found at ${path}`);
      } catch (error) {
        return Promise.resolve(`Error getting metadata: ${error instanceof Error ? error.message : String(error)}`);
      }
    },
    list_files: ({ folder_path }) => {
      try {
        const folder = app.vault.getAbstractFileByPath(folder_path || "/");
        if (folder && isFolder(folder)) {
          const files = folder.children.filter((f) => !isExcluded(f.path)).map((f) => `${isFolder(f) ? "[DIR] " : ""}${f.path}`).join("\n");
          return Promise.resolve(files || "Folder is empty or all contents are excluded");
        }
        return Promise.resolve(`Error: Folder not found at ${folder_path}`);
      } catch (error) {
        return Promise.resolve(`Error listing files: ${error instanceof Error ? error.message : String(error)}`);
      }
    },
    create_canvas: async ({ path, nodes }) => {
      if (isExcluded(path)) return `Error: Access to ${path} is excluded in settings.`;
      try {
        const canvasData = {
          nodes: nodes || [],
          edges: []
        };
        const file = await app.vault.create(path, JSON.stringify(canvasData, null, 2));
        return `Successfully created canvas at ${file.path}`;
      } catch (error) {
        return `Error creating canvas: ${error instanceof Error ? error.message : String(error)}`;
      }
    },
    add_node_to_canvas: async ({ path, node }) => {
      if (isExcluded(path)) return `Error: Access to ${path} is excluded in settings.`;
      try {
        const file = app.vault.getAbstractFileByPath(path);
        if (file && isFile(file)) {
          const content = await app.vault.read(file);
          const data = JSON.parse(content);
          data.nodes.push(node);
          await app.vault.modify(file, JSON.stringify(data, null, 2));
          return `Successfully added node to canvas at ${path}`;
        }
        return `Error: Canvas file not found at ${path}`;
      } catch (error) {
        return `Error adding node to canvas: ${error instanceof Error ? error.message : String(error)}`;
      }
    },
    create_folder: async ({ path }) => {
      try {
        await app.vault.createFolder(path);
        return `Successfully created folder at ${path}`;
      } catch (error) {
        return `Error creating folder: ${error instanceof Error ? error.message : String(error)}`;
      }
    },
    execute_command: ({ command_id }) => {
      try {
        const commands = app.commands;
        if (commands && commands.executeCommandById(command_id)) {
          return Promise.resolve(`Successfully executed command ${command_id}`);
        }
        return Promise.resolve(`Error: Command ${command_id} not found or failed to execute`);
      } catch (error) {
        return Promise.resolve(`Error executing command: ${error instanceof Error ? error.message : String(error)}`);
      }
    },
    list_commands: () => {
      try {
        const commands = app.commands;
        if (!commands || !commands.listCommands) return Promise.resolve("Error: Could not list commands");
        const list = commands.listCommands().map((c) => `${c.id}: ${c.name}`).join("\n");
        return Promise.resolve(`Available Commands:
${list}`);
      } catch (error) {
        return Promise.resolve(`Error listing commands: ${error instanceof Error ? error.message : String(error)}`);
      }
    },
    global_search: async ({ query }) => {
      try {
        const files = app.vault.getMarkdownFiles();
        const results = [];
        const lowerQuery = query.toLowerCase();
        for (const file of files) {
          if (isExcluded(file.path)) continue;
          const content = await app.vault.cachedRead(file);
          if (content.toLowerCase().includes(lowerQuery)) {
            results.push(file.path);
          }
          if (results.length >= 10) break;
        }
        return results.length > 0 ? `Found query in files:
${results.join("\n")}` : "No matches found in the vault";
      } catch (error) {
        return `Error searching vault: ${error instanceof Error ? error.message : String(error)}`;
      }
    },
    get_active_note: async () => {
      try {
        const file = app.workspace.getActiveFile();
        if (file) {
          const content = await app.vault.read(file);
          return `Active File: ${file.path}
Content:
${content}`;
        }
        return "Error: No active file found";
      } catch (error) {
        return `Error getting active file: ${error instanceof Error ? error.message : String(error)}`;
      }
    }
  };
};
var toolDeclarations = [
  {
    name: "create_note",
    description: "Erstellt eine neue Notiz im Vault",
    parameters: {
      type: "object",
      properties: {
        path: { type: "string", description: "Der Pfad der neuen Datei (z.B. 'Notizen/NeueNotiz.md')" },
        content: { type: "string", description: "Der Inhalt der Notiz" },
        tags: { type: "array", items: { type: "string" }, description: "Optionale Tags f\xFCr die Notiz" }
      },
      required: ["path", "content"]
    }
  },
  {
    name: "update_note",
    description: "\xC4ndert den Inhalt einer bestehenden Notiz",
    parameters: {
      type: "object",
      properties: {
        path: { type: "string", description: "Der Pfad der zu \xE4ndernden Datei" },
        new_content: { type: "string", description: "Der neue Inhalt der Datei" }
      },
      required: ["path", "new_content"]
    }
  },
  {
    name: "read_note",
    description: "Liest den Inhalt einer Notiz f\xFCr den Kontext",
    parameters: {
      type: "object",
      properties: {
        path: { type: "string", description: "Der Pfad der zu lesenden Datei" }
      },
      required: ["path"]
    }
  },
  {
    name: "get_metadata",
    description: "Extrahiert Frontmatter und Verlinkungen einer Datei",
    parameters: {
      type: "object",
      properties: {
        path: { type: "string", description: "Der Pfad der Datei" }
      },
      required: ["path"]
    }
  },
  {
    name: "list_files",
    description: "Listet Dateien in einem bestimmten Ordner auf",
    parameters: {
      type: "object",
      properties: {
        folder_path: { type: "string", description: "Der Pfad des Ordners (leer lassen f\xFCr den Root-Ordner)" }
      }
    }
  },
  {
    name: "create_canvas",
    description: "Erstellt eine neue Canvas-Datei (.canvas)",
    parameters: {
      type: "object",
      properties: {
        path: { type: "string", description: "Der Pfad der neuen Canvas-Datei (z.B. 'Design/Workflow.canvas')" },
        nodes: { type: "array", items: { type: "object" }, description: "Anf\xE4ngliche Knoten f\xFCr den Canvas" }
      },
      required: ["path"]
    }
  },
  {
    name: "add_node_to_canvas",
    description: "F\xFCgt einen Knoten zu einer bestehenden Canvas-Datei hinzu",
    parameters: {
      type: "object",
      properties: {
        path: { type: "string", description: "Der Pfad der Canvas-Datei" },
        node: { type: "object", description: "Der hinzuzuf\xFCgende Knoten (mit id, x, y, width, height, type, text/file/etc.)" }
      },
      required: ["path", "node"]
    }
  },
  {
    name: "create_folder",
    description: "Erstellt einen neuen Ordner im Vault",
    parameters: {
      type: "object",
      properties: {
        path: { type: "string", description: "Der Pfad des neuen Ordners (z.B. 'Projekte/AI-Agent')" }
      },
      required: ["path"]
    }
  },
  {
    name: "execute_command",
    description: "F\xFChrt einen Obsidian-Befehl anhand seiner ID aus (entspricht der Command Palette)",
    parameters: {
      type: "object",
      properties: {
        command_id: { type: "string", description: "Die ID des Befehls (z.B. 'app:toggle-left-sidebar')" }
      },
      required: ["command_id"]
    }
  },
  {
    name: "list_commands",
    description: "Listet alle verf\xFCgbaren Obsidian-Befehle auf, damit der Agent wei\xDF, was er steuern kann",
    parameters: { type: "object", properties: {} }
  },
  {
    name: "global_search",
    description: "Sucht im gesamten Vault nach einem bestimmten Textinhalt (Inhaltssuche)",
    parameters: {
      type: "object",
      properties: {
        query: { type: "string", description: "Der zu suchende Text" }
      },
      required: ["query"]
    }
  },
  {
    name: "get_active_note",
    description: "Holt den Pfad und Inhalt der aktuell im Editor ge\xF6ffneten Notiz",
    parameters: { type: "object", properties: {} }
  }
];

// src/suggest.ts
var import_obsidian = require("obsidian");
var FileSuggestModal = class extends import_obsidian.FuzzySuggestModal {
  onSelect;
  constructor(app, onSelect) {
    super(app);
    this.onSelect = onSelect;
    this.setPlaceholder("Select a file to attach as context...");
  }
  getItems() {
    return this.app.vault.getMarkdownFiles();
  }
  getItemText(file) {
    return file.path;
  }
  onChooseItem(file, _evt) {
    this.onSelect(file);
  }
};

// src/view.ts
var THINKING_TIPS = [
  "Tip: Use # to attach a file for more context.",
  "Did you know? Gemini can create and edit Obsidian Canvas files.",
  "Idea: Ask Gemini to summarize your meeting notes.",
  "Tip: You can exclude sensitive folders in the plugin settings.",
  "Did you know? Gemini 1.5 Pro has a massive context window.",
  "Idea: Ask for a mind-map based on your current project.",
  "Tip: Use @mention logic coming soon for even better workflow.",
  "Pro-Tip: Clear chat frequently to keep the context focused."
];
var THINKING_QUOTES = [
  '"The only way to do great work is to love what you do." - Steve Jobs',
  '"Knowledge is power." - Francis Bacon',
  '"Design is not just what it looks like and feels like. Design is how it works." - Steve Jobs',
  '"Simplicity is the ultimate sophistication." - Leonardo da Vinci',
  '"Focus on being productive instead of busy." - Tim Ferriss',
  '"Your mind is for having ideas, not holding them." - David Allen'
];
var GeminiChatView = class extends import_obsidian2.ItemView {
  plugin;
  messageContainer;
  inputField;
  chat = null;
  abortController = null;
  isLoading = false;
  currentConversation = null;
  searchQuery = "";
  showArchived = false;
  lastUserMessage = "";
  headerTitleEl;
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.navigation = true;
    this.icon = "gemini-sparkle";
    console.debug("Gemini: view instance created");
  }
  getViewType() {
    return VIEW_TYPE_GEMINI_CHAT;
  }
  getDisplayText() {
    return "Gemini chat";
  }
  onClose() {
    this.cancelRequest();
    return Promise.resolve();
  }
  cancelRequest() {
    if (this.abortController) {
      this.abortController.abort();
      this.abortController = null;
    }
    this.setLoading(false);
  }
  setLoading(loading) {
    this.isLoading = loading;
    if (loading) {
      this.containerEl.addClass("is-loading");
    } else {
      this.containerEl.removeClass("is-loading");
    }
  }
  onOpen() {
    this.renderOverview();
  }
  renderOverview() {
    const container = this.contentEl;
    container.empty();
    container.addClass("gemini-chat-view-container");
    const header = container.createDiv("gemini-chat-header");
    header.createEl("h4", { text: "Conversations" });
    const headerActions = header.createDiv("gemini-header-actions");
    const archiveToggle = headerActions.createEl("button", {
      cls: "clickable-icon" + (this.showArchived ? " is-active" : ""),
      title: "Show archived"
    });
    (0, import_obsidian2.setIcon)(archiveToggle, "archive");
    archiveToggle.onclick = () => {
      this.showArchived = !this.showArchived;
      this.renderOverview();
    };
    const newChatBtn = headerActions.createEl("button", { cls: "clickable-icon", title: "New chat" });
    (0, import_obsidian2.setIcon)(newChatBtn, "plus");
    newChatBtn.onclick = () => void this.startNewChat();
    const searchContainer = container.createDiv("gemini-search-container");
    const searchInput = searchContainer.createEl("input", {
      type: "text",
      placeholder: "Search chats...",
      cls: "gemini-search-input"
    });
    searchInput.value = this.searchQuery;
    searchInput.oninput = (e) => {
      this.searchQuery = e.target.value;
      this.renderConversationList(listContainer);
    };
    const listContainer = container.createDiv("gemini-conversation-list");
    this.renderConversationList(listContainer);
  }
  renderConversationList(container) {
    container.empty();
    const convs = this.plugin.conversationManager.getConversations(this.showArchived, this.searchQuery);
    if (convs.length === 0) {
      container.createDiv({ text: this.searchQuery ? "No matches found" : "No conversations yet", cls: "gemini-empty-state" });
      return;
    }
    convs.forEach((conv) => {
      const item = container.createDiv("gemini-conversation-item");
      if (conv.isArchived) item.addClass("is-archived");
      const info = item.createDiv("gemini-conv-info");
      info.createDiv({ text: conv.title, cls: "gemini-conv-title" });
      info.createDiv({ text: new Date(conv.updatedAt).toLocaleString(), cls: "gemini-conv-date" });
      info.onclick = () => void this.loadConversation(conv);
      const actions = item.createDiv("gemini-conv-actions");
      const archiveBtn = actions.createEl("button", { cls: "clickable-icon", title: conv.isArchived ? "Unarchive" : "Archive" });
      (0, import_obsidian2.setIcon)(archiveBtn, conv.isArchived ? "eye" : "archive");
      archiveBtn.onclick = async (e) => {
        e.stopPropagation();
        this.plugin.conversationManager.archiveConversation(conv.id, !conv.isArchived);
        await this.plugin.saveSettings();
        this.renderConversationList(container);
      };
      const deleteBtn = actions.createEl("button", { cls: "clickable-icon", title: "Delete" });
      (0, import_obsidian2.setIcon)(deleteBtn, "trash-2");
      deleteBtn.onclick = async (e) => {
        e.stopPropagation();
        this.plugin.conversationManager.deleteConversation(conv.id);
        await this.plugin.saveSettings();
        this.renderConversationList(container);
        new import_obsidian2.Notice("Conversation deleted");
      };
    });
  }
  async startNewChat() {
    this.currentConversation = this.plugin.conversationManager.createConversation();
    this.currentConversation.model = this.plugin.settings.modelName;
    await this.plugin.saveSettings();
    this.renderChatInterface();
    await this.initializeChat();
  }
  async loadConversation(conv) {
    this.currentConversation = conv;
    this.renderChatInterface();
    for (const msg of conv.messages) {
      let displayContent = msg.parts[0].text;
      if (msg.role === "user" && displayContent.includes("\nUser request: ")) {
        displayContent = displayContent.split("\nUser request: ").pop() || displayContent;
      }
      await this.appendMessage(msg.role === "user" ? "user" : "agent", displayContent, false);
    }
    await this.initializeChat(conv.messages.map((m) => ({
      role: m.role,
      parts: m.parts
    })));
  }
  renderChatInterface() {
    const container = this.contentEl;
    container.empty();
    const header = container.createDiv("gemini-chat-header");
    const backBtn = header.createEl("button", { cls: "clickable-icon", title: "Back to overview" });
    (0, import_obsidian2.setIcon)(backBtn, "arrow-left");
    backBtn.onclick = () => this.renderOverview();
    this.headerTitleEl = header.createEl("h4", { text: this.currentConversation?.title || "Gemini AI Agent", cls: "gemini-header-title" });
    const modelSelect = header.createEl("select", { cls: "gemini-model-select-ui" });
    this.plugin.availableModels.forEach((mId) => {
      const opt = modelSelect.createEl("option", { text: MODEL_DISPLAY_NAMES[mId] || mId, value: mId });
      if (mId === (this.currentConversation?.model || this.plugin.settings.modelName)) opt.selected = true;
    });
    modelSelect.onchange = async () => {
      if (this.currentConversation) {
        this.currentConversation.model = modelSelect.value;
        await this.plugin.saveSettings();
        await this.initializeChat(this.currentConversation.messages);
      }
    };
    this.messageContainer = container.createDiv("gemini-chat-messages");
    const inputWrapper = container.createDiv("gemini-chat-input-wrapper");
    const inputContainer = inputWrapper.createDiv("gemini-chat-input-container");
    this.inputField = inputContainer.createEl("textarea", {
      placeholder: "Ask Gemini... (use # to attach files)",
      cls: "gemini-chat-input"
    });
    this.inputField.addEventListener("input", () => {
      this.inputField.setCssProps({ height: "auto" });
      this.inputField.setCssProps({ height: this.inputField.scrollHeight + "px" });
    });
    this.inputField.addEventListener("keydown", (e) => {
      if (e.key === "#") {
        setTimeout(() => {
          new FileSuggestModal(this.app, (file) => {
            const value = this.inputField.value;
            const lastHashIndex = value.lastIndexOf("#");
            this.inputField.value = value.substring(0, lastHashIndex) + `[[${file.path}]] `;
            this.inputField.focus();
            this.inputField.dispatchEvent(new Event("input"));
          }).open();
        }, 10);
      }
      if (e.key === "ArrowUp" && this.inputField.value === "" && this.lastUserMessage) {
        this.inputField.value = this.lastUserMessage;
        this.inputField.dispatchEvent(new Event("input"));
      }
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.handleSendMessage();
      }
    });
    const sendButton = inputContainer.createEl("button", { cls: "gemini-send-button", title: "Send" });
    (0, import_obsidian2.setIcon)(sendButton, "send");
    sendButton.onclick = () => void this.handleSendMessage();
  }
  async initializeChat(history = []) {
    if (this.plugin.genAI) {
      try {
        const modelId = this.currentConversation?.model || this.plugin.settings.modelName;
        const model = await this.plugin.getModelWithFallback(modelId);
        const modelWithTools = this.plugin.genAI.getGenerativeModel({
          model: model.model,
          tools: [{ functionDeclarations: toolDeclarations }]
        });
        const cleanHistory = history.map((msg) => ({
          role: msg.role,
          parts: msg.parts
        }));
        this.chat = modelWithTools.startChat({ history: cleanHistory });
      } catch (error) {
        await this.appendMessage("agent", `Error initializing chat: ${error instanceof Error ? error.message : String(error)}`);
      }
    }
  }
  async handleSendMessage() {
    const originalMessage = this.inputField.value.trim();
    if (!originalMessage || this.isLoading || !this.currentConversation) return;
    this.lastUserMessage = originalMessage;
    const fileMentions = originalMessage.match(/\[\[(.*?)\]\]/g);
    let contextPrefix = "";
    if (fileMentions) {
      for (const mention of fileMentions) {
        const path = mention.replace("[[", "").replace("]]", "");
        const file = this.app.vault.getAbstractFileByPath(path);
        if (file instanceof import_obsidian2.TFile) {
          const content = await this.app.vault.cachedRead(file);
          contextPrefix += `
Content of "${path}":
${content}
---
`;
        }
      }
    }
    const finalPrompt = contextPrefix ? `${contextPrefix}
User request: ${originalMessage}` : originalMessage;
    await this.appendMessage("user", originalMessage);
    this.currentConversation.messages.push({
      role: "user",
      parts: [{ text: finalPrompt }],
      timestamp: Date.now()
    });
    this.inputField.value = "";
    this.inputField.style.setProperty("height", "auto");
    if (!this.plugin.genAI) {
      await this.appendMessage("agent", "Error: API Key not configured.");
      return;
    }
    if (!this.chat) await this.initializeChat();
    if (!this.chat) return;
    this.setLoading(true);
    const randomTip = THINKING_TIPS[Math.floor(Math.random() * THINKING_TIPS.length)];
    const randomQuote = THINKING_QUOTES[Math.floor(Math.random() * THINKING_QUOTES.length)];
    const thinkingMsg = await this.appendMessage("agent", "Thinking...");
    thinkingMsg.addClass("gemini-thinking-wrapper");
    const contentEl = thinkingMsg.firstElementChild;
    if (contentEl) {
      contentEl.empty();
      const thinkingContainer = contentEl.createDiv("gemini-thinking-container");
      thinkingContainer.createDiv("gemini-thinking-shimmer").textContent = "Gemini is processing your request...";
      const infoPanel = thinkingContainer.createDiv("gemini-thinking-info");
      infoPanel.createDiv("gemini-thinking-tip").textContent = randomTip;
      infoPanel.createDiv("gemini-thinking-quote").textContent = randomQuote;
      const toolStatus = thinkingContainer.createDiv("gemini-tool-status");
      try {
        this.abortController = new AbortController();
        let result = await this.chat.sendMessage(finalPrompt);
        let response = await result.response;
        let iterations = 0;
        const MAX_ITERATIONS = 5;
        while (iterations < MAX_ITERATIONS && response.candidates && response.candidates[0].content.parts.some((part) => !!part.functionCall)) {
          iterations++;
          const toolResults = [];
          const excludedPaths = this.plugin.settings.excludedPaths.split(",").filter((p) => p.trim() !== "");
          const tools = getObsidianTools(this.app, excludedPaths);
          for (const part of response.candidates[0].content.parts) {
            if (part.functionCall) {
              const name = part.functionCall.name;
              const args = part.functionCall.args;
              toolStatus.textContent = `Executing tool: ${name}...`;
              const toolFunction = tools[name];
              const resultText = toolFunction ? await toolFunction(args) : `Tool ${name} not found`;
              toolResults.push({
                functionResponse: { name, response: { result: resultText } }
              });
            }
          }
          result = await this.chat.sendMessage(toolResults);
          response = await result.response;
        }
        const responseText = response.text();
        thinkingMsg.remove();
        if (responseText) {
          await this.appendMessage("agent", responseText);
          this.currentConversation.messages.push({
            role: "model",
            parts: [{ text: responseText }],
            timestamp: Date.now()
          });
          if (this.currentConversation.title === "New Chat") {
            await this.generateAutoTitle(originalMessage, responseText);
          }
        }
        await this.plugin.saveSettings();
      } catch (error) {
        if (thinkingMsg) thinkingMsg.remove();
        if (error.name === "AbortError") {
          await this.appendMessage("agent", "_Request cancelled_");
        } else {
          await this.appendMessage("agent", `**Error:** ${error.message}`);
        }
      } finally {
        this.abortController = null;
        this.setLoading(false);
      }
    }
  }
  async generateAutoTitle(userMsg, aiMsg) {
    if (!this.plugin.genAI || !this.currentConversation) return;
    try {
      const model = this.plugin.genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
      const prompt = `Generiere einen sehr kurzen, pr\xE4gnanten Titel (max 5 W\xF6rter) f\xFCr diesen Chat-Anfang. Gib NUR den Titel zur\xFCck, keine Anf\xFChrungszeichen:
Nutzer: ${userMsg}
KI: ${aiMsg}`;
      const result = await model.generateContent(prompt);
      const title = result.response.text().trim();
      if (title) {
        this.currentConversation.title = title;
        if (this.headerTitleEl) this.headerTitleEl.textContent = title;
        await this.plugin.saveSettings();
      }
    } catch (e) {
      console.error("Failed to generate title", e);
    }
  }
  async appendMessage(sender, text, scroll = true) {
    const msgEl = this.messageContainer.createDiv(`gemini-message gemini-message-${sender}`);
    const contentEl = msgEl.createDiv("gemini-message-content");
    if (sender === "agent" && text !== "Thinking..." && !text.includes("Gemini is processing")) {
      await import_obsidian2.MarkdownRenderer.render(this.app, text, contentEl, "", this);
      const actionsEl = msgEl.createDiv("gemini-message-actions");
      const copyBtn = actionsEl.createEl("button", { cls: "gemini-action-btn", title: "Copy to clipboard" });
      (0, import_obsidian2.setIcon)(copyBtn, "copy");
      copyBtn.onclick = () => {
        navigator.clipboard.writeText(text);
        new import_obsidian2.Notice("Copied to clipboard");
      };
      const retryBtn = actionsEl.createEl("button", { cls: "gemini-action-btn", title: "Regenerate" });
      (0, import_obsidian2.setIcon)(retryBtn, "refresh-cw");
      retryBtn.onclick = () => {
        if (this.currentConversation && this.currentConversation.messages.length > 0) {
          this.currentConversation.messages.pop();
          const lastUserMsg = this.currentConversation.messages.pop();
          if (lastUserMsg) {
            this.inputField.value = lastUserMsg.parts[0].text.split("\nUser request: ").pop() || lastUserMsg.parts[0].text;
            this.handleSendMessage();
          }
        }
      };
    } else {
      contentEl.textContent = text;
    }
    if (scroll) this.messageContainer.scrollTop = this.messageContainer.scrollHeight;
    return msgEl;
  }
};

// node_modules/.pnpm/uuid@13.0.0/node_modules/uuid/dist/stringify.js
var byteToHex = [];
for (let i = 0; i < 256; ++i) {
  byteToHex.push((i + 256).toString(16).slice(1));
}
function unsafeStringify(arr, offset = 0) {
  return (byteToHex[arr[offset + 0]] + byteToHex[arr[offset + 1]] + byteToHex[arr[offset + 2]] + byteToHex[arr[offset + 3]] + "-" + byteToHex[arr[offset + 4]] + byteToHex[arr[offset + 5]] + "-" + byteToHex[arr[offset + 6]] + byteToHex[arr[offset + 7]] + "-" + byteToHex[arr[offset + 8]] + byteToHex[arr[offset + 9]] + "-" + byteToHex[arr[offset + 10]] + byteToHex[arr[offset + 11]] + byteToHex[arr[offset + 12]] + byteToHex[arr[offset + 13]] + byteToHex[arr[offset + 14]] + byteToHex[arr[offset + 15]]).toLowerCase();
}

// node_modules/.pnpm/uuid@13.0.0/node_modules/uuid/dist/rng.js
var getRandomValues;
var rnds8 = new Uint8Array(16);
function rng() {
  if (!getRandomValues) {
    if (typeof crypto === "undefined" || !crypto.getRandomValues) {
      throw new Error("crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported");
    }
    getRandomValues = crypto.getRandomValues.bind(crypto);
  }
  return getRandomValues(rnds8);
}

// node_modules/.pnpm/uuid@13.0.0/node_modules/uuid/dist/native.js
var randomUUID = typeof crypto !== "undefined" && crypto.randomUUID && crypto.randomUUID.bind(crypto);
var native_default = { randomUUID };

// node_modules/.pnpm/uuid@13.0.0/node_modules/uuid/dist/v4.js
function _v4(options, buf, offset) {
  options = options || {};
  const rnds = options.random ?? options.rng?.() ?? rng();
  if (rnds.length < 16) {
    throw new Error("Random bytes length must be >= 16");
  }
  rnds[6] = rnds[6] & 15 | 64;
  rnds[8] = rnds[8] & 63 | 128;
  if (buf) {
    offset = offset || 0;
    if (offset < 0 || offset + 16 > buf.length) {
      throw new RangeError(`UUID byte range ${offset}:${offset + 15} is out of buffer bounds`);
    }
    for (let i = 0; i < 16; ++i) {
      buf[offset + i] = rnds[i];
    }
    return buf;
  }
  return unsafeStringify(rnds);
}
function v4(options, buf, offset) {
  if (native_default.randomUUID && !buf && !options) {
    return native_default.randomUUID();
  }
  return _v4(options, buf, offset);
}
var v4_default = v4;

// src/conversations.ts
var ConversationManager = class {
  conversations = [];
  constructor(data) {
    if (data && Array.isArray(data.conversations)) {
      this.conversations = data.conversations;
    }
  }
  createConversation(title = "New Chat") {
    const newConv = {
      id: v4_default(),
      title,
      messages: [],
      updatedAt: Date.now(),
      isArchived: false
    };
    this.conversations.unshift(newConv);
    return newConv;
  }
  getConversations(includeArchived = false, search = "") {
    return this.conversations.filter((c) => includeArchived || !c.isArchived).filter((c) => c.title.toLowerCase().includes(search.toLowerCase())).sort((a, b) => b.updatedAt - a.updatedAt);
  }
  getConversation(id) {
    return this.conversations.find((c) => c.id === id);
  }
  updateConversation(conv) {
    const index = this.conversations.findIndex((c) => c.id === conv.id);
    if (index !== -1) {
      conv.updatedAt = Date.now();
      if (conv.messages.length > 20) {
        conv.messages = conv.messages.slice(-20);
      }
      this.conversations[index] = conv;
    }
  }
  garbageCollect(maxConversations = 50, maxAgeDays = 30) {
    const now = Date.now();
    const maxAgeMs = maxAgeDays * 24 * 60 * 60 * 1e3;
    this.conversations = this.conversations.filter((c) => {
      if (c.isArchived) return true;
      const age = now - c.updatedAt;
      return age < maxAgeMs;
    });
    if (this.conversations.length > maxConversations) {
      const active = this.conversations.filter((c) => !c.isArchived);
      const archived = this.conversations.filter((c) => c.isArchived);
      if (active.length > maxConversations) {
        const truncatedActive = active.sort((a, b) => b.updatedAt - a.updatedAt).slice(0, maxConversations);
        this.conversations = [...truncatedActive, ...archived];
      }
    }
  }
  deleteConversation(id) {
    this.conversations = this.conversations.filter((c) => c.id !== id);
  }
  archiveConversation(id, archive = true) {
    const conv = this.getConversation(id);
    if (conv) {
      conv.isArchived = archive;
      this.updateConversation(conv);
    }
  }
  toJSON() {
    return this.conversations;
  }
};

// src/main.ts
var VIEW_TYPE_GEMINI_CHAT = "gemini-chat-view";
var GEMINI_ICON = `<svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M12 22C12 22 11.5 17 8 13.5C4.5 10 0 9.5 0 9.5C0 9.5 4.5 9 8 5.5C11.5 2 12 0 12 0C12 0 12.5 2 16 5.5C19.5 9 24 9.5 24 9.5C24 9.5 19.5 10 16 13.5C12.5 17 12 22 12 22Z" fill="currentColor"/>
</svg>`;
var MODEL_DISPLAY_NAMES = {
  "gemini-2.0-flash": "Gemini 2.0 Flash (Fast)",
  "gemini-2.0-flash-exp": "Gemini 2.0 Flash Experimental",
  "gemini-1.5-pro": "Gemini 1.5 Pro (Complex Tasks)",
  "gemini-1.5-flash": "Gemini 1.5 Flash (Efficient)",
  "gemini-1.5-flash-8b": "Gemini 1.5 Flash 8B (Super Fast)",
  "auto": "\u2728 Auto-Select (Smart Fallback)"
};
var DEFAULT_SETTINGS = {
  apiKey: "",
  modelName: "auto",
  excludedPaths: "",
  autoAcceptTools: true,
  conversations: []
};
var GeminiAgentPlugin2 = class extends import_obsidian3.Plugin {
  settings;
  genAI = null;
  availableModels = ["auto", "gemini-2.0-flash", "gemini-1.5-pro", "gemini-1.5-flash"];
  conversationManager;
  async onload() {
    await this.loadSettings();
    this.conversationManager = new ConversationManager(this.settings);
    this.conversationManager.garbageCollect();
    await this.logToFile("Plugin loading...");
    await this.refreshModels();
    (0, import_obsidian3.addIcon)("gemini-sparkle", GEMINI_ICON);
    this.registerView(
      VIEW_TYPE_GEMINI_CHAT,
      (leaf) => new GeminiChatView(leaf, this)
    );
    this.addRibbonIcon("gemini-sparkle", "Gemini chat", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-gemini-chat",
      name: "Open Gemini chat",
      callback: () => {
        void this.activateView();
      }
    });
    this.addCommand({
      id: "open-gemini-chat-center",
      name: "Open Gemini chat in center tab (for testing)",
      callback: () => {
        void this.activateView(true);
      }
    });
    this.addCommand({
      id: "gemini-debug-info",
      name: "Debug Gemini plugin state",
      callback: async () => {
        const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_GEMINI_CHAT);
        const status = `
					API Key set: ${!!this.settings.apiKey}
					GenAI initialized: ${!!this.genAI}
					Available models: ${this.availableModels.length}
					Active leaves: ${leaves.length}
				`;
        await this.logToFile(`Debug Info requested: ${status}`);
        new import_obsidian3.Notice(`Gemini Debug: ${leaves.length} leaves found. Check log file for details.`);
      }
    });
    this.addCommand({
      id: "refresh-gemini-models",
      name: "Refresh available models",
      callback: async () => {
        await this.refreshModels();
        await this.logToFile("Models refreshed manually");
        new import_obsidian3.Notice("Gemini models refreshed");
      }
    });
    this.addCommand({
      id: "summarize-current-note",
      name: "Summarize current note",
      checkCallback: (checking) => {
        const file = this.app.workspace.getActiveFile();
        if (file) {
          if (!checking) {
            void this.summarizeNote(file);
          }
          return true;
        }
        return false;
      }
    });
    this.addSettingTab(new GeminiAgentSettingTab(this.app, this));
    await this.logToFile("Plugin loaded successfully");
  }
  async refreshModels() {
    if (!this.genAI) return;
    try {
      const response = await (0, import_obsidian3.requestUrl)({
        url: `https://generativelanguage.googleapis.com/v1beta/models?key=${this.settings.apiKey}`,
        method: "GET"
      });
      const data = response.json;
      if (data.models) {
        const apiModels = data.models.map((m) => m.name.replace("models/", "")).filter((name) => name.includes("gemini"));
        this.availableModels = ["auto", ...apiModels];
      }
    } catch (error) {
      console.error("Failed to fetch models:", error);
    }
  }
  async getModelWithFallback(preferredModel) {
    if (!this.genAI) throw new Error("GenAI not initialized");
    let modelsToTry = [preferredModel];
    if (preferredModel === "auto" || preferredModel === "") {
      modelsToTry = ["gemini-2.0-flash", "gemini-1.5-pro", "gemini-1.5-flash"];
    } else {
      if (!modelsToTry.includes("gemini-1.5-flash")) modelsToTry.push("gemini-1.5-flash");
    }
    let lastError = null;
    for (const modelName of modelsToTry) {
      try {
        const model = this.genAI.getGenerativeModel({ model: modelName });
        return model;
      } catch (error) {
        lastError = error instanceof Error ? error : new Error(String(error));
        if (lastError.message?.includes("429") || lastError.message?.includes("quota") || lastError.message?.includes("not found")) {
          console.warn(`Model ${modelName} failed, trying fallback...`, lastError);
          continue;
        }
        throw lastError;
      }
    }
    throw lastError || new Error("Failed to initialize model");
  }
  async summarizeNote(file) {
    if (!this.genAI || !this.settings) {
      new import_obsidian3.Notice("Gemini API key not configured");
      return;
    }
    new import_obsidian3.Notice(`Summarizing ${file.basename}...`);
    try {
      const content = await this.app.vault.read(file);
      const model = await this.getModelWithFallback(this.settings.modelName);
      const prompt = `Fasse folgende Notiz kurz und pr\xE4gnant zusammen:

${content}`;
      const result = await model.generateContent(prompt);
      const response = await result.response;
      const summary = response.text();
      await this.app.fileManager.processFrontMatter(file, (frontmatter) => {
        frontmatter["summary"] = summary;
      });
      new import_obsidian3.Notice("Summary added to frontmatter");
    } catch (error) {
      new import_obsidian3.Notice(`Error: ${error instanceof Error ? error.message : String(error)}`);
      console.error(error);
    }
  }
  async logToFile(message, isError = false) {
    const timestamp = (/* @__PURE__ */ new Date()).toISOString();
    const logLine = `[${timestamp}] ${isError ? "ERROR" : "INFO"} ${message}
`;
    console.debug(`Gemini: ${message}`);
    try {
      const logPath = "gemini-agent-debug.log";
      const adapter = this.app.vault.adapter;
      if (await adapter.exists(logPath)) {
        const currentContent = await adapter.read(logPath);
        await adapter.write(logPath, currentContent + logLine);
      } else {
        await adapter.write(logPath, logLine);
      }
    } catch (e) {
      console.error("Failed to write to log file:", e);
    }
  }
  async activateView(center = false) {
    try {
      await this.logToFile(`Activating view (center: ${center})...`);
      const { workspace } = this.app;
      const leaves = workspace.getLeavesOfType(VIEW_TYPE_GEMINI_CHAT);
      let leaf = null;
      if (leaves.length > 0) {
        await this.logToFile(`Found ${leaves.length} existing leaves`);
        leaf = leaves[0];
      } else {
        await this.logToFile(`Creating new leaf (mode: ${center ? "center" : "right"})`);
        const newLeaf = center ? workspace.getLeaf("tab") : workspace.getRightLeaf(false);
        if (newLeaf) {
          await this.logToFile("Setting view state...");
          await newLeaf.setViewState({
            type: VIEW_TYPE_GEMINI_CHAT,
            active: true
          });
          leaf = newLeaf;
          await this.logToFile("View state set successfully");
        } else {
          await this.logToFile("Could not get a leaf from workspace", true);
        }
      }
      if (leaf) {
        await this.logToFile("Revealing leaf");
        workspace.revealLeaf(leaf);
        new import_obsidian3.Notice("Gemini chat opened");
      } else {
        await this.logToFile("Failed to find or create leaf (leaf is null)", true);
        new import_obsidian3.Notice("Error: Could not open Gemini chat. See log file.");
      }
    } catch (error) {
      await this.logToFile(`CRITICAL ERROR in activateView: ${error.message}`, true);
      if (error.stack) await this.logToFile(`Stack: ${error.stack}`, true);
      new import_obsidian3.Notice("Critical error opening Gemini chat. Check log file.");
    }
  }
  onunload() {
    console.debug("Gemini agent plugin unloaded");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    const secretKey = this.app.secretStorage.getSecret("gemini-api-key");
    if (secretKey) {
      this.settings.apiKey = secretKey;
    }
    if (this.settings.apiKey) {
      this.genAI = new GoogleGenerativeAI(this.settings.apiKey);
    }
  }
  async saveSettings() {
    if (this.conversationManager) {
      this.settings.conversations = this.conversationManager.toJSON();
    }
    await this.saveData(this.settings);
    if (this.settings.apiKey) {
      this.app.secretStorage.setSecret("gemini-api-key", this.settings.apiKey);
    } else {
      this.app.secretStorage.setSecret("gemini-api-key", "");
    }
    if (this.settings.apiKey) {
      this.genAI = new GoogleGenerativeAI(this.settings.apiKey);
    } else {
      this.genAI = null;
    }
    new import_obsidian3.Notice("Gemini settings saved");
  }
};
var GeminiAgentSettingTab = class extends import_obsidian3.PluginSettingTab {
  plugin;
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian3.Setting(containerEl).setHeading().setName("Gemini AI agent settings");
    new import_obsidian3.Setting(containerEl).setName("Google Gemini API key").setDesc("Enter your Google Gemini API key. It will be stored securely in your system keychain.").addText(
      (text) => text.setPlaceholder("Enter your API key").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value;
        await this.plugin.saveSettings();
      }).inputEl.type = "password"
    );
    new import_obsidian3.Setting(containerEl).setName("Model").setDesc("Choose the Gemini model to use.").addDropdown((dropdown) => {
      this.plugin.availableModels.forEach((model) => {
        dropdown.addOption(model, MODEL_DISPLAY_NAMES[model] || model);
      });
      dropdown.setValue(this.plugin.settings.modelName).onChange(async (value) => {
        this.plugin.settings.modelName = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Auto-accept tools").setDesc("If enabled, the agent can execute Obsidian tools automatically. If disabled, you might need to confirm actions (not yet implemented in UI).").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoAcceptTools).onChange(async (value) => {
        this.plugin.settings.autoAcceptTools = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Excluded paths").setDesc('Comma-separated list of paths or folders to exclude from the AI agent (e.g. "Private/, SecretNote.md").').addTextArea(
      (text) => text.setPlaceholder("Enter paths to exclude").setValue(this.plugin.settings.excludedPaths).onChange(async (value) => {
        this.plugin.settings.excludedPaths = value;
        await this.plugin.saveSettings();
      })
    );
  }
};
/*! Bundled license information:

@google/generative-ai/dist/index.mjs:
@google/generative-ai/dist/index.mjs:
  (**
   * @license
   * Copyright 2024 Google LLC
   *
   * Licensed under the Apache License, Version 2.0 (the "License");
   * you may not use this file except in compliance with the License.
   * You may obtain a copy of the License at
   *
   *   http://www.apache.org/licenses/LICENSE-2.0
   *
   * Unless required by applicable law or agreed to in writing, software
   * distributed under the License is distributed on an "AS IS" BASIS,
   * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   * See the License for the specific language governing permissions and
   * limitations under the License.
   *)
*/
